Update French translation
alainm23/planify pull request #167
Opened 2020-01-26 11:25 UTC by yannicka

2020-01-26 18:14 UTC, NathanBnm requested changes
I left some comments, but here are some others comments I couldn't place in my review:
The following string has not been translated. I can't find context for it and literal translation won't fit well.
```
#: src/Widgets/Pane.vala:52
msgid "Back-Pocket"
msgstr "" 
```
Here a space is missing before the semicolon.
```diff
#: src/Widgets/ReminderButton.vala:172
msgid "Time:"
-msgstr "Heure:"
+msgstr "Heure :"
```
This string is marked as fuzzy. What format should it be?
```
#: src/Widgets/Calendar/CalendarHeader.vala:34
#, fuzzy
msgid "%OB, %Y"
msgstr "%e %B %Y"
```
The colon is missing to the following strings:
```diff
#: src/Views/Welcome.vala:29
msgid "Start working locally."
-msgstr "Commencez à travailler localement"
+msgstr "Commencez à travailler localement."
```
```diff
#: src/Views/Welcome.vala:30
msgid "Synchronize with your Todoist account and start working."
-msgstr "Synchronisez avec votre compte Todoist et commencez à travailler"
+msgstr "Synchronisez avec votre compte Todoist et commencez à travailler."
```
This translation sounds better in French (and the colon is missing):
```diff
#: src/Dialogs/TodoistOAuth.vala:83
msgid "Synchronizing… Wait a moment please."
-msgstr "Synchronisation… Attendez un instant s'il vous plaît"
+msgstr "Synchronisation… Veuillez patienter un instant."
```
Translation suggestion here too:
```diff
#: src/Dialogs/TodoistOAuth.vala:95
msgid "Please enter your credentials…"
-msgstr "Veuillez saisir vos informations d'identification…"
+msgstr "Veuillez saisir vos identifiants…"
```
The app name should not be translated:
```diff
#: src/Dialogs/Preferences.vala:348
msgid ""
"Personalize the look and feel of your Planner by choosing the theme that "
"best suits you."
msgstr ""
-"Personnalisez l'apparence de votre planificateur en choisissant le thème qui "
-"vous convient le mieux."
+"Personnalisez l'apparence de Planner en choisissant le thème qui "
+"vous convient le mieux."
```

Plus you forgot to translate the changelog.

2020-01-26 18:14 UTC, NathanBnm commented on po/fr.po
> +msgstr "Garder une trace de vos tâches"
```suggestion
msgstr "Gardez un œil sur vos tâches"
```

2020-01-26 18:14 UTC, NathanBnm commented on po/fr.po
> +msgstr "Erreur de création de projet Todoist"
```suggestion
msgstr "Erreur de création du projet Todoist"
```

2020-01-26 18:14 UTC, NathanBnm commented on po/fr.po
> +"à internet. Les changements que vous\n"
```suggestion
"à Internet. Les changements que vous\n"
```
@alainm23 you should capitalize the word 'Internet'.

2020-01-26 18:14 UTC, NathanBnm commented on po/fr.po
>  msgstr "Source:"
```suggestion
msgstr "Source :"
```
Space is missing

2020-01-26 18:14 UTC, NathanBnm commented on po/fr.po
> +"Démarrer un nouveau projet, créer une liste de choses à faire, organisez vos "
```suggestion
"Démarrez un nouveau projet, créez une liste de choses à faire, organisez vos "
```

2020-01-26 18:14 UTC, NathanBnm commented on po/fr.po
> +msgstr "Organiser vos projets en groupes et garder votre panneau propre."
```suggestion
msgstr "Organisez vos projets en groupes et gardez votre panneau propre."
```

2020-01-26 18:14 UTC, NathanBnm commented on po/fr.po
> +msgstr "Projet de groupe"
```suggestion
msgstr "Groupe de projet"
```

2020-01-26 18:14 UTC, NathanBnm commented on po/fr.po
> +msgstr "Terminée"
```suggestion
msgstr "Marquer comme terminé"
```
Depending of the context

2020-01-26 18:14 UTC, NathanBnm commented on po/fr.po
>  msgstr "Masquer les tâches complétées"
```suggestion
msgstr "Date de fin"
```

2020-01-26 18:14 UTC, NathanBnm commented on po/fr.po
>  msgstr "Masquer les tâches complétées"
I can't suggest it in this review but you have to remove the fuzzy attribute above.

2020-01-26 18:14 UTC, NathanBnm commented on po/fr.po
>  msgstr "Créer une étiquette"
Please remove the fuzzy attribute above.

2020-01-26 18:14 UTC, NathanBnm commented on po/fr.po
> +msgstr "Nom de la sous-stâche"
```suggestion
msgstr "Nom de la sous-tâche"
```

2020-01-26 18:14 UTC, NathanBnm commented on po/fr.po
> +msgstr "Chercher une tâche"
```suggestion
msgstr "Rechercher une tâche"
```

2020-01-26 18:14 UTC, NathanBnm commented on po/fr.po
> +msgstr "24 h"
```suggestion
msgstr "24h"
```

2020-01-26 18:14 UTC, NathanBnm commented on po/fr.po
> +msgstr "Financement"
```suggestion
msgstr "Soutenir"
```
Depending of the context

2020-01-26 18:50 UTC, yannicka commented on po/fr.po
> +msgstr "24 h"
The space is correct

2020-01-26 18:54 UTC, yannicka commented on po/fr.po
> +"à internet. Les changements que vous\n"
"internet" may or may not be capitalized. There is no reason to capitalize it.

2020-01-26 18:56 UTC, yannicka commented on po/fr.po
>  msgstr "Masquer les tâches complétées"
I did not translate this chain because I am not sure of the translation.

2020-01-26 19:13 UTC, yannicka commented
I took your proposals into account, thank you.

2020-01-26 19:42 UTC, NathanBnm commented on po/fr.po
> +"à internet. Les changements que vous\n"
"Internet" should be capitalized if we talk about "the Internet" but not if used as an adjective like "site internet" in French.

2020-01-26 19:44 UTC, NathanBnm commented on po/fr.po
>  msgstr "Masquer les tâches complétées"
I suggest "Date de fin", because "Date de complétion" sounds bad

2020-01-26 21:08 UTC, yannicka commented on po/fr.po
> +"à internet. Les changements que vous\n"
"internet" *may* be capitalized, not *should*.

2020-01-26 22:08 UTC, yannicka commented on po/fr.po
> +"à internet. Les changements que vous\n"
I think that discussing it here is useless and will not help. Nobody is wrong, nobody is right. Suggest another PR if you want. Don't hesitate to do a PR if you think the use of "internet" without capitalization is incorrect.

2020-01-27 02:06 UTC, merged

2020-01-27 02:06 UTC, alainm23 commented
Thank you so much guys.