Update it.po
alainm23/planify pull request #193
Opened 2020-01-31 20:46 UTC by albanobattistella

2020-02-02 13:07 UTC, albanobattistella commented
Hi,

I fixed but checks failed?

2020-02-03 02:48 UTC, alainm23 commented
Thank you very much for your translation. I'm sorry I couldn't review this earlier. There are some syntax errors, I would recommend that you use [Poedit](https://poedit.net/) so that you can worry only about the translation.

2020-02-03 02:49 UTC, alainm23 requested changes
Thank you very much for your translation. I'm sorry I couldn't review this earlier. There are some syntax errors, I would recommend that you use [Poedit](https://poedit.net/) so that you can worry only about the translation.

2020-02-03 02:49 UTC, alainm23 commented on po/it.po
> +"priorità in modo da sapere esattamente su cosa si deve concentrarsi e quando.
The string has not been closed `"`

2020-02-03 02:49 UTC, alainm23 commented on po/it.po
> +"- Nel menu delle opzioni seleziona" Progetto "e digita il nome del tuo nuovo"
A syntax error.

2020-02-03 02:49 UTC, alainm23 commented on po/it.po
> +"agenda per i prossimi giorni: cose da fare e eventi del calendario programmati".
syntax error

2020-02-03 02:49 UTC, alainm23 commented on po/it.po
> +"annullarlo.""
Two quotes are invalid.

2020-02-03 02:49 UTC, alainm23 commented on po/it.po
> +"Tutte le scorciatoie per farti risparmiare tempo! Alcune possono essere utilizzate ovunque nell'app",
syntax error

2020-02-03 02:49 UTC, alainm23 commented on po/it.po
> +"voglia".
Delete the point

2020-02-03 02:49 UTC, alainm23 commented on po/it.po
> +"I menu del pianificatore sono stati riprogettati. Rendendolo più bello e produttivo.
end-of-line within string

2020-02-03 02:49 UTC, alainm23 commented on po/it.po
> +"[GitHub # 145, # 146] - È stato migliorato il modo di creare il progetto tutorial.
end-of-line within string

2020-02-03 02:49 UTC, alainm23 commented on po/it.po
> +"Opzione "\"senza data\."
syntax error

2020-02-03 11:12 UTC, alainm23 commented
Could you send in a new PR please? I've updated the tradition files.

2020-02-03 14:24 UTC, albanobattistella commented
Ok...Will be done!
________________________________
Da: Alain <notifications@github.com>
Inviato: lunedì 3 febbraio 2020 12:12:31
A: alainm23/planner <planner@noreply.github.com>
Cc: albanobattistella <albano_battistella@hotmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [alainm23/planner] Update it.po (#193)


Could you send in a new PR please? I've updated the tradition files.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/alainm23/planner/pull/193?email_source=notifications&email_token=AIJS6FBLVJXAFPNNQFTCQUTRA73Z7A5CNFSM4KONKTSKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKTN6DA#issuecomment-581361420>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AIJS6FDIPTSAGKZYL6UFVIDRA73Z7ANCNFSM4KONKTSA>.

2020-02-03 19:35 UTC, albanobattistella commented
done!

2020-02-03 21:02 UTC, merged

2020-02-03 21:03 UTC, alainm23 commented
Thanks :)